# Generated by Django 4.2 on 2023-04-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='baby_gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
