# Generated by Django 4.2 on 2023-04-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_app_user_baby_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='session_invite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
