# Generated by Django 4.2 on 2023-04-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_app_user_session_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='other_parent',
            field=models.CharField(blank=True, null=True),
        ),
    ]
