# Generated by Django 4.2 on 2023-04-17 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('popularity', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Session_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(blank=True, null=True)),
                ('parent_1_choice', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_2_choice', models.CharField(blank=True, max_length=10, null=True)),
                ('agreed', models.CharField(blank=True, max_length=1, null=True)),
                ('manual_add', models.CharField(blank=True, max_length=1, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('baby_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='names_app.baby_names', verbose_name='baby_name')),
                ('parent1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent1', to=settings.AUTH_USER_MODEL)),
                ('parent2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
