# Generated by Django 4.2 on 2023-04-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_names',
            name='session_gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
