# Generated by Django 4.2 on 2023-04-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('names_app', '0002_session_names_session_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_names',
            name='baby_name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_name', to='names_app.baby_names'),
        ),
    ]
